version: 2
# formats: all
build:
  os: ubuntu-24.04
  tools:
    python: "3.10"
  jobs:
    post_checkout:
      - git fetch --unshallow
python:
    install:
        - requirements: docs/requirements.txt
        - method: pip
          path: .
sphinx:
    configuration: docs/source/conf.py
    fail_on_warning: true
