#
# Use S/N from target Magewell USB Capture device, or specify "auto"
# value to pickup first available USB Capture device.
# Can use `lsusb -d 2935: -v  | grep iSer` to discover available.
#
# The ones we have just FTR:
#device_serial_number: "B208180921036"  # for con/noisure
#device_serial_number: "B208220302195"  # reprostim
device_serial_number: "auto"

#
# Specify basic pattern for possible video device path locations,
# syntax is the same as pattern parameter in "glob" Linux API. This
# parameter used only when "ffm_opts.v_dev" parameter set to "auto".
#
video_device_path_pattern: "/dev/video*"

# Specify capture session file logger settings
# it is used to log capture session related information to file
# located in output directory and named like output file
# with ".log" extension.

# to enable session file logger set "session_logger_enabled" to "true"
session_logger_enabled: true

# specify session file logger level (DEBUG, INFO, WARN, ERROR)
session_logger_level: "DEBUG"

# specify session log line format, from spdlog library
session_logger_pattern: "%Y-%m-%d %H:%M:%S.%e [%l] [%t] %v"

#
# Specific to reprostim-screencapture options
#
sc_opts:
  # Specifies diff threshold to detect changes in the screen
  threshold: 400000
  # bool, specifies whether to dump raw frames to disk along
  # with PNG screenshots. Useful for debugging.
  dump_raw: false
  # Specifies obligatory snapshot capture interval in ms. When
  # value  is greater than 0 , then snapshot will  be captured
  # at least  every specified period.
  interval_ms: 0




