#!/bin/bash
#
# A simple script to ensure that birch has SD card mounted
#
mount=/mnt/td
# shellcheck disable=SC2029
ssh birch "mount | grep -q -e '$mount\>'" || { echo "BIRCH does not have $mount mounted"; exit 1; }
