#!/bin/bash

set -u 
cd $(dirname $0)

source venvs/dev3/bin/activate || { echo "Failed to start venv"; exit 1; }

while true; do 
	ts=$(date --iso-8601=seconds)
	echo "$ts starting" >> log
	./dev_run.sh -l data/$ts.csv WAVESHARE_RP2040-Zero
	echo "$ts exited with $?" >> log
	sleep 60; 
done
