#!/bin/bash

set -eu 
cd $(dirname $0)

while true; do 
	ts=$(date --iso-8601=seconds)
	echo "$ts starting" >> log
	./dev_run.sh -l data/$ts.csv XIAO-RP2040
	echo "$ts exited with $?" >> log
	sleep 60; 
done
