---
#
# Use S/N from target Magewell USB Capture device, or specify "auto"
# value to pickup first available USB Capture device.
# Can use `lsusb -d 2935: -v  | grep iSer` to discover available.
#
# The ones we have just FTR:
#device_serial_number: "B208180921036"  # for con/noisure
#device_serial_number: "B208220302195"  # reprostim
device_serial_number: "auto"

#
# Specify basic pattern for possible video device path locations,
# syntax is the same as pattern parameter in "glob" Linux API. This
# parameter used only when "ffm_opts.v_dev" parameter set to "auto".
#
video_device_path_pattern: "/dev/video*"

# Specify capture session file logger settings
# it is used to log capture session related information to file
# located in output directory and named like output file
# with ".log" extension.

# to enable session file logger set "session_logger_enabled" to "true"
session_logger_enabled: true

# specify session file logger level (DEBUG, INFO, WARN, ERROR)
session_logger_level: "DEBUG"

# specify session log line format, from spdlog library
session_logger_pattern: "%Y-%m-%d %H:%M:%S.%e [%l] [%t] %v"

#
# Specify con/duct options to execute ffmpeg command
#
conduct_opts:
    # to enable con/duct set "enabled" to "true"
    enabled: false
    # cmd template
    #cmd: "echo '${ffmpeg_cmd}'"
    cmd: "duct --sample-interval 10 --report-interval 60 ${ffmpeg_cmd}"

#
# Specify ReproNim/repromon options
#
repromon_opts:
  # to enable repromon set "enabled" to "true"
  enabled: false
  api_base_url: "https://localhost:9095/api/1"
  # specify repromon api key directly or via env macro ${REPROMON_API_KEY}
  api_key: "${REPROMON_API_KEY}"
  # specify SSL certificate verification is required, default is true
  verify_ssl_cert: false
  # specify repromon data provider (REPROSTIM=2, NOISSEUR=5)
  data_provider_id: 2
  # specify used MRI device (DBIC=1)
  device_id: 1
  # specify repromon message category (FEEDBACK=1)
  message_category_id: 1
  # specify repromon logger level (INFO=1, WARN=2, ERROR=3)
  message_level_id: 1


#
# Video capture ffmpeg recording options
#
ffm_opts:
  a_fmt: "-f alsa"
  a_nchan: "-ac 2"
  #
  # Optionally, specify "a_dev" ALSA audio device explicitly (e.g. hw:1,0)
  # to override value calculated from "device_serial_number" or specify
  # "auto" value, to calculate "a_dev" automatically based on
  # "device_serial_number" value.
  # To specify audio subdevice explicitly in auto mode it can be added
  # after comma (,) e.g. "auto,0"
  #
  a_dev: "auto"
  a_opt: "-thread_queue_size 4096"
  #
  # Optionally, specify "a_vol" to set audio volume level
  # for "line-in" and "hdmi" audio inputs
  # use (0% - 100%) to set volume level in percentage
  # or integer number to set volume level in device raw units
  #
  a_vol:
    line-in: "95%"
    hdmi: "95%"

  v_fmt: "-f v4l2 -input_format yuyv422"
  v_opt: "-thread_queue_size 4096"
  #
  # Optionally, specify "v_dev" explicitly to override value
  # calculated from "device_serial_number" value or specify
  # "auto" value, to calculate "v_dev" automatically based on
  # "device_serial_number" value
  #
  # NOTE: in case v_dev specified explicitly, a_dev value
  # should be also specified explicitly
  #
  #v_dev: "/dev/video4"
  v_dev: "auto"
  v_enc: "-c:v libx264 -flush_packets 1 -preset ultrafast -crf 18 -tune zerolatency -b:v 2M -maxrate 2M -bufsize 4M -vf setpts=PTS-STARTPTS"
  pix_fmt: ""
  #pix_fmt: "-pix_fmt yuv420p"
  n_threads: "-threads 4"
  a_enc: "-acodec aac -af asetpts=PTS-STARTPTS"
  out_fmt: "mkv"
