---
ffm_opts:
  a_fmt: "-f alsa" 
  a_nchan: "-ac 2" 
  a_dev: "-i hw:1,1"
  a_opt: "-thread_queue_size 4096"
  v_fmt: "-f v4l2 -input_format yuyv422" 
  v_opt: "-thread_queue_size 4096" 
  v_dev: "/dev/video0"
  v_enc: "-c:v copy"
  pix_fmt: ""
  n_threads: ""
  a_enc: "-acodec aac"
  out_fmt: "mkv"
