name: Build Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Docker Image
        run: |
          (
            echo "$PWD"

            echo "Docker images BEFORE build:"
            docker images

            export REPROSTIM_CAPTURE_ENABLED=1
            export REPROSTIM_DOCKER_TAGS="master unstable"
            ./build_reprostim_container.sh docker

            echo "Docker images AFTER build:"
            docker images
          )
        working-directory: tools/ci

      - name: Test Docker Container Run
        run: |
          # build only if not release tag, and has some "-" in describe
          # so we do not duplicate work with release workflow.
          git describe --match '[0-9]*\.[0-9]*\.[0-9]*' | grep -q -e - && \
          (
            echo "$PWD"
            export REPROSTIM_CONTAINER_TYPE=docker
            # specify latest unstable image to test
            export REPROSTIM_CONTAINER_IMAGE=repronim/reprostim:unstable
            ./test_reprostim_container.sh
            ./test_reprostim_psychopy.sh xvfb
          )
        working-directory: tools/ci

      - name: Push Docker Image
        # publish to docker hub only on push to master branch
        if: github.event_name == 'push'
        run: |
          git describe --match '[0-9]*\.[0-9]*\.[0-9]*' | grep -q -e - && \
          (
            REPROSTIM_VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
            echo "Pushing Docker image with version: $REPROSTIM_VERSION"
            docker login -u "$DOCKER_LOGIN" --password-stdin <<<"$DOCKER_TOKEN"
            docker push repronim/reprostim:master
            docker push repronim/reprostim:unstable
          )
        env:
          DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

      - name: Upload Screenshot Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: reprostim-psychopy-screenshot
          path: |
            ${{ env.tmp_dir }}/reprostim_psychopy_screenshot.png
            ${{ env.tmp_dir }}/reprostim_psychopy.log
