name: Update Docker Hub Description

on:
  workflow_dispatch:  # Allows manual triggering from GitHub UI
  push:
    branches:
      - master
    paths:
      - 'containers/repronim-reprostim/DOCKERHUB.md'
  pull_request:
    branches:
      - master
    paths:
      - 'containers/repronim-reprostim/DOCKERHUB.md'

permissions:
  contents: read

jobs:
  update-description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: repronim/reprostim
          readme-filepath: ./containers/repronim-reprostim/DOCKERHUB.md
          short-description: "ReproStim: Reproducible stimuli delivery and synchronization toolkit for neuroimaging"