name: Build Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Build Docker Image
        run: |
          (
            echo "$PWD"
            export REPROSTIM_CAPTURE_ENABLED=1
            ./build_reprostim_container.sh docker
          )
        working-directory: tools/ci
