name: Build Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Docker Image
        run: |
          (
            echo "$PWD"
            export REPROSTIM_CAPTURE_ENABLED=1
            ./build_reprostim_container.sh docker
          )
        working-directory: tools/ci

      - name: Test Docker Container Run
        run: |
          (
            echo "$PWD"
            export REPROSTIM_CONTAINER_TYPE=docker
            ./test_reprostim_container.sh
          )
        working-directory: tools/ci

      - name: Push Docker Image
        run: |
          (
            REPROSTIM_VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
            echo "Pushing Docker image with version: $REPROSTIM_VERSION"
            docker login -u "$DOCKER_LOGIN" --password-stdin <<<"$DOCKER_TOKEN"
            docker push repronim/reprostim:${REPROSTIM_VERSION}
            docker push repronim/reprostim:latest
          )
        env:
          DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
