name: Docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  docs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python:
          - '3.10'
          #- 3.11
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        # Fetch all commits so that versioneer will return something compatible
        # with semantic-version
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r docs/requirements.txt

    - name: Install reprostim
      run: |
        pip install -e .

    - name: Build docs
      run: |
        cd docs
        make html

#    - name: Upload docs/artifacts
#      uses: actions/upload-artifact@v4
#      with:
#        name: sphinx-docs
#        path: docs/_build/html/

#    - name: Deploy to github pages
#      if: github.ref == 'refs/heads/main'
#      uses: peaceiris/actions-gh-pages@v4
#      with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}
#         publish_dir: docs/_build/html
